### ISSUE TITLE
Fix workaround after nuxt generate

### ISSUE THREAD

**Issue by rosolowski** [edmcouncil/devops#23]
https://github.com/edmcouncil/devops/blob/2ae431a2dff804f3e8006864fb0be01dc2460b33/jenkins/html-pages/Jenkinsfile#L90
The "move" command will not be needed anymore.

**Comment by przemekgradzki** [comment]
For now, just "improving" this workaround (_move_ command) - to maintain backward compatibility.
Once the edmcouncil/html-pages#403 is fully deployed, this workaround will be removed
