### ISSUE TITLE
Time limits for consistency check

### ISSUE THREAD

**Issue by przemekgradzki** [edmcouncil/devops#30]
The _hygiene_ stage:
https://github.com/edmcouncil/devops/blob/09ebca2a7221d97c9a5cf992bb4336362f42864a/jenkins/idmp/Jenkinsfile#L191

 should be limited in time, as there are situations in which it lasts up to several days - see [idmp:PR-469#106](https://jenkins.edmcouncil.org/view/all/job/idmp/view/change-requests/job/PR-469/106/).

See also:
- edmcouncil/ontology-publisher#155
- [FIBO-678: Time limits for consistency check](https://jira.makolab.net/browse/FIBO-678)

**Comment by mereolog** [comment]
Also can we revert the order with hygiene tests, i.e.,

1. first we run the hygiene tests
2. then we run the consistency check.
